<?php
$data = array (
  338 => 
  array (
    'cat_id' => '338',
    'cat_name' => '商品分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '338',
    'name' => '商品分类',
  ),
  323 => 
  array (
    'cat_id' => '323',
    'cat_name' => '特产',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '323',
    'name' => '特产',
  ),
  333 => 
  array (
    'cat_id' => '333',
    'cat_name' => '香菇',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '333',
    'name' => '香菇',
  ),
  334 => 
  array (
    'cat_id' => '334',
    'cat_name' => '山茱萸',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '334',
    'name' => '山茱萸',
  ),
  331 => 
  array (
    'cat_id' => '331',
    'cat_name' => '核桃',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '331',
    'name' => '核桃',
  ),
  335 => 
  array (
    'cat_id' => '335',
    'cat_name' => '板栗',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '335',
    'name' => '板栗',
  ),
  332 => 
  array (
    'cat_id' => '332',
    'cat_name' => '黑木耳',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '332',
    'name' => '黑木耳',
  ),
  337 => 
  array (
    'cat_id' => '337',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '1',
    'level' => 1,
    'id' => '337',
    'name' => '茶叶',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '高山野山茶',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '343',
    'name' => '高山野山茶',
  ),
  341 => 
  array (
    'cat_id' => '341',
    'cat_name' => '商南绿茶',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '341',
    'name' => '商南绿茶',
  ),
  340 => 
  array (
    'cat_id' => '340',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '340',
    'name' => '铁观音',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '普洱',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '344',
    'name' => '普洱',
  ),
  345 => 
  array (
    'cat_id' => '345',
    'cat_name' => '龙井',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '345',
    'name' => '龙井',
  ),
  321 => 
  array (
    'cat_id' => '321',
    'cat_name' => '酒品',
    'measure_unit' => '件',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '321',
    'name' => '酒品',
  ),
  324 => 
  array (
    'cat_id' => '324',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '13',
    'level' => 2,
    'id' => '324',
    'name' => '葡萄酒',
  ),
  339 => 
  array (
    'cat_id' => '339',
    'cat_name' => '情人醉',
    'measure_unit' => '1000',
    'parent_id' => '324',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '339',
    'name' => '情人醉',
  ),
  325 => 
  array (
    'cat_id' => '325',
    'cat_name' => '山茱萸酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '325',
    'name' => '山茱萸酒',
  ),
  326 => 
  array (
    'cat_id' => '326',
    'cat_name' => '黑枸杞酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '326',
    'name' => '黑枸杞酒',
  ),
  322 => 
  array (
    'cat_id' => '322',
    'cat_name' => '食品',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '322',
    'name' => '食品',
  ),
  330 => 
  array (
    'cat_id' => '330',
    'cat_name' => '柿子饼',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '330',
    'name' => '柿子饼',
  ),
  327 => 
  array (
    'cat_id' => '327',
    'cat_name' => '香菇酱',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '327',
    'name' => '香菇酱',
  ),
  328 => 
  array (
    'cat_id' => '328',
    'cat_name' => '香菇丝',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '328',
    'name' => '香菇丝',
  ),
  329 => 
  array (
    'cat_id' => '329',
    'cat_name' => '食用醋',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '329',
    'name' => '食用醋',
  ),
);
?>