<?php
$data = array (
  0 => 
  array (
    'cat_id' => '338',
    'cat_name' => '商品分类',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '324',
    'cat_name' => '葡萄酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '13',
  ),
  2 => 
  array (
    'cat_id' => '325',
    'cat_name' => '山茱萸酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '326',
    'cat_name' => '黑枸杞酒',
    'measure_unit' => '',
    'parent_id' => '321',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '330',
    'cat_name' => '柿子饼',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '327',
    'cat_name' => '香菇酱',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  6 => 
  array (
    'cat_id' => '328',
    'cat_name' => '香菇丝',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '329',
    'cat_name' => '食用醋',
    'measure_unit' => '',
    'parent_id' => '322',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '333',
    'cat_name' => '香菇',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '334',
    'cat_name' => '山茱萸',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '331',
    'cat_name' => '核桃',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '335',
    'cat_name' => '板栗',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '332',
    'cat_name' => '黑木耳',
    'measure_unit' => '',
    'parent_id' => '323',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '339',
    'cat_name' => '情人醉',
    'measure_unit' => '1000',
    'parent_id' => '324',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '343',
    'cat_name' => '高山野山茶',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '341',
    'cat_name' => '商南绿茶',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '340',
    'cat_name' => '铁观音',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '344',
    'cat_name' => '普洱',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '345',
    'cat_name' => '龙井',
    'measure_unit' => '',
    'parent_id' => '337',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '323',
    'cat_name' => '特产',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '337',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '1',
  ),
  21 => 
  array (
    'cat_id' => '321',
    'cat_name' => '酒品',
    'measure_unit' => '件',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '322',
    'cat_name' => '食品',
    'measure_unit' => '',
    'parent_id' => '338',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
);
?>